# 🌺💜 Violet: Extended C++ standard library
# Copyright (c) 2025-2026 Noelware, LLC. <team@noelware.org>, et al.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

load("//buildsystem/bazel:cc.bzl", "violet_cc_library", "violet_cc_test")

package(
    default_visibility = ["//visibility:public"],
)

violet_cc_library(
    name = "basic_awaiter",
    hdrs = ["//include/violet/Experimental/Coroutines:BasicAwaiter.h"],
    copts = select({
        # GCC requires `-fcoroutines` to be passed through in-case people
        # forget to `-fcoroutines`.
        "@rules_cc//cc/compiler:gcc": ["-fcoroutines"],
        "//conditions:default": [],
    }),
    deps = ["//violet/experimental:tuple"],
)

violet_cc_library(
    name = "generator",
    hdrs = ["//include/violet/Experimental/Coroutines:Generator.h"],
    copts = select({
        # GCC requires `-fcoroutines` to be passed through in-case people
        # forget to `-fcoroutines`.
        "@rules_cc//cc/compiler:gcc": ["-fcoroutines"],
        "//conditions:default": [],
    }),
    deps = [
        "//violet:iterator",
        "//violet/experimental:oneof",
    ],
)

violet_cc_test(
    name = "generator_test",
    srcs = ["//tests/experimental/coroutines:Generator.test.cc"],
    deps = [
        ":generator",
        "//violet/iterator:filter",
    ],
)

violet_cc_library(
    name = "join_handle",
    hdrs = ["//include/violet/Experimental/Coroutines:JoinHandle.h"],
    deps = [
        "//violet/experimental/coroutines/internals:scheduler",
        "//violet/experimental/coroutines/internals:spawned_task",
    ],
)

violet_cc_library(
    name = "runtime",
    srcs = ["//src/experimental/coroutines:Runtime.cc"],
    hdrs = ["//include/violet/Experimental/Coroutines:Runtime.h"],
    deps = [
        ":join_handle",
        ":task",
        "//violet/experimental:unique",
        "//violet/experimental/coroutines/internals/schedulers:single_threaded",
        "//violet/experimental/coroutines/internals/timers:driver",
        "//violet/experimental/time:clock",
    ],
)

violet_cc_test(
    name = "runtime_test",
    srcs = ["//tests/experimental/coroutines:Runtime.test.cc"],
    deps = [":runtime"],
)

violet_cc_library(
    name = "sleep",
    srcs = ["//src/experimental/coroutines:Sleep.cc"],
    hdrs = ["//include/violet/Experimental/Coroutines:Sleep.h"],
    deps = [
        ":runtime",
        "//violet/experimental/coroutines/internals/timers:wheel",
    ],
)

violet_cc_test(
    name = "sleep_test",
    srcs = ["//tests/experimental/coroutines:Sleep.test.cc"],
    deps = [":sleep"],
)

violet_cc_library(
    name = "task",
    hdrs = ["//include/violet/Experimental/Coroutines:Task.h"],
    copts = select({
        # GCC requires `-fcoroutines` to be passed through in-case people
        # forget to `-fcoroutines`.
        "@rules_cc//cc/compiler:gcc": ["-fcoroutines"],
        "//conditions:default": [],
    }),
    deps = [
        "//violet:defer",
        "//violet/experimental:oneof",
    ],
)

violet_cc_test(
    name = "task_test",
    srcs = ["//tests/experimental/coroutines:Task.test.cc"],
    deps = [":task"],
)

violet_cc_library(
    name = "waker",
    srcs = ["//src/experimental/coroutines:Waker.cc"],
    hdrs = ["//include/violet/Experimental/Coroutines:Waker.h"],
    deps = ["//violet/experimental/coroutines/internals:raw_task"],
)
