#!/usr/bin/env bash
# +---------------------------------------------------------------------------------+
# 🌺💜 Violet: Extended C++ standard library
# Copyright (c) 2025-2026 Noelware, LLC. <team@noelware.org>, et al.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
# +----------------------------------------------------------------------------------

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." &> /dev/null && pwd)
VERSION=$(cat "$SCRIPT_DIR/.violet-version")

echo "[violet/tools:mesondist] Preparing Meson distribution..."

dir="$SCRIPT_DIR/.mesondist"
[ -d "$dir" ] && rm -rf "$dir" || true

# Create a directory in the script directory so that we can copy files into this for the final tarball
mkdir -p "$dir"

dirs=(
    "include"
    "src"
    "hack"
    "tests"
)

files=(
    ".violet-version"
    "meson.build"
    "meson_options.txt"
    "README.md"
    "LICENSE"
    "CHANGELOG.md"
)

for dirent in "${dirs[@]}"; do
    echo "[violet/tools:mesondist] copying directory $dir ~> $dir/$dirent"
    cp -r "$SCRIPT_DIR/$dirent" "$dir"

    if [ "$dirent" == "hack" ]; then
        rm -rf "$dir/hack/nix"
        rm "$dir/hack/build-ci-images.sh"
    fi
done

for file in "${files[@]}"; do
    echo "[violet/tools:mesondist] copying file $file ~> $dir/$file"
    cp -f "$SCRIPT_DIR/$file" "$dir"
done

echo "[violet/tools:mesondist] repackaging \`.mesondist\` as a tarball file with a determinstic timestamp"
GZIP=-n tar \
  -C "$SCRIPT_DIR/.mesondist" \
  --mtime='@0' \
  --sort=name \
  --owner=0 --group=0 --numeric-owner \
  -czvf "$SCRIPT_DIR/mesondist.tgz" \
  .

echo "now available at $SCRIPT_DIR/mesondist.tgz"
